# @package _global_

defaults:
  - _self_
  - datamodule: datamodule_gesture_generation_beat.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: gesture_diffusion_lightningmodule_beat.yaml
  - logger: wandb.yaml
  - trainer: gpu.yaml
  - paths: path_gesture_generation.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /home/lingling/code/DiffmotionEmotionGesture_v1/logs/gesture_generation/runs/2023-07-22_14-20-28/checkpoints/epoch_029.ckpt
