_target_: src.datamodules.gesture_datamodule_beat.GestureDataModule

data_dir: ${paths.data_dir} # data_dir is specified in config.yaml
#data_dir: '/home/zf223669/Mount/DiffusionGestureGeneration/data/GesturesData'
framerate: 20
seqlen: 5
n_lookahead: 20
dropout: 0.2
batch_size: 256 #80
#input_size: 972
input_size: 36266 #beat audio
num_workers: 16 #16
#input_size: 1017
